# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Hayden/Desktop/ExportBack/CoCO_Studios/studio55/studio55.cache/wt [current_project]
set_property parent.project_path C:/Users/Hayden/Desktop/ExportBack/CoCO_Studios/studio55/studio55.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Hayden/Desktop/ExportBack/CoCO_Studios/studio55/studio55.srcs/sources_1/new/a74x148priorityencoder8to3.vhd
  C:/Users/Hayden/Desktop/ExportBack/CoCO_Studios/studio55/studio55.srcs/sources_1/new/a74x138decoder3to8.vhd
  C:/Users/Hayden/Desktop/ExportBack/CoCO_Studios/studio55/studio55.srcs/sources_1/new/toplevel5.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Hayden/Desktop/ExportBack/CoCO_Studios/studio55/studio55.srcs/constrs_1/new/testenc.xdc
set_property used_in_implementation false [get_files C:/Users/Hayden/Desktop/ExportBack/CoCO_Studios/studio55/studio55.srcs/constrs_1/new/testenc.xdc]


synth_design -top toplevel5 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef toplevel5.dcp

catch { report_utilization -file toplevel5_utilization_synth.rpt -pb toplevel5_utilization_synth.pb }
